---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: any-old-app-devl
  namespace: devl
spec:
  dependsOn:
  - name: any-old-app-devl
    namespace: flux-system
  interval: 1m0s
  path: ./flux
  prune: false
  sourceRef:
    kind: GitRepository
    name: any-old-app-main
  targetNamespace: devl
  validation: client
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: any-old-app-version
